### ISSUE TITLE
Index Khala governance

### ISSUE THREAD

**Issue by bdmason** [litentry/subsquid-mappings-khala#6]
We need to know how many times an account has participated in a vote. For now this could be a schema as simple as:

```
type Governance @entity {
  id: ID! # substrate address
  votes: BigInt!
}
```

This work will use `subsquid` via the `subsquid-mappings` repository. This repo currently has no useful mappings, so it can be renamed to `subsquid-mappings-khala` as we need a subsquid repo per network.

**Comment by geastwood** [comment]
```
type Governance @entity {
  ...
  votes: [Vote!]!
  totalVotes: BigInt!
}
```

Would make more sense to me.

**Comment by geastwood** [comment]
btw, is it also possible to query like, an address `A` votes in year `2022`, or in general a specific time range?

**Comment by geastwood** [comment]
Renaming this repo for Phala is fine, also it may make sense to convert this repo also to a template repo. So save us time in the future when we integrate other networks.

**Comment by bdmason** [comment]
> btw, is it also possible to query like, an address A votes in year 2021, or in general a specific time range?

yes, with your suggested schema that's possible
